### ISSUE TITLE
How do you select the .zim file ?

### ISSUE THREAD

**Issue by TR3re** [IMayBeABitShy/pyzim#1]
I tried to use the example shown in iter.py but how do I use the path to my .zim file ? It is not really clear for me. 
I used the command : `python iter.py path/to/zim` and I got an error message. I tried to add the path inside the code but It doesn't work either. Do you have an exemple on how to clearly select the zim file to use the iter.py on ?

**Comment by IMayBeABitShy** [comment]
Hi, sorry for the late reply.

> I used the command : python iter.py path/to/zim

That command should work. Could you share the exception?

This may sound dumb, but have you verified that the path is actually correct? The `path` argument [is passed directly to pythons `open`](https://github.com/IMayBeABitShy/pyzim/blob/master/pyzim/archive.py#L224) function, so pyzim should be capable of opening any file that python can open. Perhaps it's a permission issue? Or something simple to overerlook - like using the wrong type of path separators (e.g. using `/` instead of `\\` on windows)? You can test that python can open a file by running `python -c "open('path/to/file.zim', mode='r').close()"`.

Or do you get some ZIM-related exception (e.g. file incompatible)?

Also, be sure you use python 3 (see `python --version`, though usually it is invoked via the python3 command).

**Comment by TR3re** [comment]
Hi, no worries. Here's the output of the command. 
```
C:\Users\TR3\Desktop\WIKI\pyzim>python iter.py 'wikipedia_en_100_maxi_2024-04.zim'
Traceback (most recent call last):
  File "C:\Users\TR3\Desktop\WIKI\pyzim\iter.py", line 97, in <module>
    main()
  File "C:\Users\TR3\Desktop\WIKI\pyzim\iter.py", line 36, in main
    with pyzim.Zim.open(zimpath) as zim:
  File "C:\Users\TR3\AppData\Local\Programs\Python\Python310\lib\site-packages\pyzim\archive.py", line 201, in open
    f = open(path, fmode)
FileNotFoundError: [Errno 2] No such file or directory: "'wikipedia_en_100_maxi_2024-04.zim'"
```
the zim file is inside the same directory as the iter.py
I tried to use `python -c "open('path/to/file.zim', mode='r').close()"` but it did nothing, using the full path or using \\\ but it throwed some more errors. 
It might be some dumb issue ^^' I don't really use windows for those kind of thing but I have some issues with Python on my Linux so I didn't have a choice.

**Comment by IMayBeABitShy** [comment]
> File "C:\Users\TR3\AppData\Local\Programs\Python\Python310\lib\site-packages\pyzim\archive.py", line 201, in open
    f = open(path, fmode)
FileNotFoundError: [Errno 2] No such file or directory: "'wikipedia_en_100_maxi_2024-04.zim'"

This indicates that python itself can indeed not find the file.

> the zim file is inside the same directory as the iter.py

Did you remember to adjust the path so it respects your CWD (meaning that any relative path you pass to the program needs to be relative to the directory you are currently working in, not to `iter.py`)?

Just to be sure, try the following:

1. place the ZIM inside any directory (can be the same as `iter.py`)
2. ensure your CWD is the same as the directory the ZIM file is located in (on linux, use `cd path/to/directory`, but you probably already know this.
3. Confirm that the path is correct - when running `ls` (on linux, IIRC the windows command would be `dir`) it should list "wikipedia_en_100_maxi_2024-04.zim" (or whatever ZIM you use) as a file. If not, your CWD is wrong.
4. run `python3 /path/to/iter.py wikipedia_en_100_maxi_2024-04.zim`

> I tried to use python -c "open('path/to/file.zim', mode='r').close()" but it did nothing, using the full path or using \\ but it throwed some more errors.

If it threw some exception, that would indicate that this issue is unrelated to pyzim. If it did not raise any exception, then python can access the file and the problem must be with the way the path is being passed to `open()`.

> No such file or directory: "'wikipedia_en_100_maxi_2024-04.zim'"

Actually, I just noticed the that the file name in the error message uses both single and double quotation marks. This indicates that python believes the `'` to be part of the filename. Have you tried it without the quotation marks?

> I don't really use windows for those kind of thing but I have some issues with Python on my Linux so I didn't have a choice.

Have you tried a python virtual environment? These are very easy to setup isolated python environments that can avoid dependency related problems and may help in your case:

1.  `apt-get python3-venv` (or similiar)
2. `python3 -m venv path/to/some/directory`
3. `source /path/to/some/directory/bin/activate`
4. Now `python3` and `pip` use an isolated environment

**Comment by TR3re** [comment]
I tried every step and this is what I got in the end : 
```
(myenv) casper@casper-desktop:~/pyzim$ python3 iter.py wikipedia_en_100_maxi_2024-04.zim 
Traceback (most recent call last):
  File "/home/casper/myenv/lib/python3.11/site-packages/pyzim/archive.py", line 862, in get_entry_by_full_url
    location = self._url_pointer_list.get(full_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casper/myenv/lib/python3.11/site-packages/pyzim/pointerlist.py", line 408, in get
    return self._pointers[self.get_index(key)]
                          ^^^^^^^^^^^^^^^^^^^
  File "/home/casper/myenv/lib/python3.11/site-packages/pyzim/pointerlist.py", line 428, in get_index
    raise KeyError("No pointer matching key '{}' found!".format(key))
KeyError: "No pointer matching key 'b'Xlisting/titleOrdered/v1'' found!"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/casper/pyzim/iter.py", line 60, in <module>
    main()
  File "/home/casper/pyzim/iter.py", line 36, in main
    with pyzim.Zim.open(zimpath) as zim:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casper/myenv/lib/python3.11/site-packages/pyzim/archive.py", line 202, in open
    archive = cls(f, mode=mode, policy=policy)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casper/myenv/lib/python3.11/site-packages/pyzim/archive.py", line 135, in __init__
    self._load_pointerlists()
  File "/home/casper/myenv/lib/python3.11/site-packages/pyzim/archive.py", line 322, in _load_pointerlists
    self.get_entry_by_full_url(constants.URL_ARTICLE_TITLE_INDEX).read(),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/casper/myenv/lib/python3.11/site-packages/pyzim/archive.py", line 864, in get_entry_by_full_url
    raise EntryNotFound("No entry for full URL '{}'".format(full_url))
pyzim.exceptions.EntryNotFound: No entry for full URL 'Xlisting/titleOrdered/v1'
```
![image](https://github.com/IMayBeABitShy/pyzim/assets/88163598/517dc00b-d5a5-4e52-94a2-e71143c01e43)

**Comment by IMayBeABitShy** [comment]
So, great news:

1. this is a different  (and unrelated) error than the one you've encountered first, it seems like we've sorted that problem out
2. this new error has already fixed seven months ago - seems like I've forgotten to push the newest version to pypi. Sorry about that, totally my fault. I'll try to push the new version sometime later. Until then, you can install the version directly from github (either clone the repo or use `pip install git+https://github.com/IMayBeABitShy/pyzim.git`). I've just tested it with wikipedia_en_100_maxi_2024-04.zim, so I am fairly sure that it should work.

**Comment by TR3re** [comment]
Thank you so much ! I was almost going crazy.
